# Generated by Django 4.0.1 on 2022-01-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_images_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='file_name',
            new_name='file',
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='image 1', max_length=50),
            preserve_default=False,
        ),
    ]
