# Generated by Django 4.0.1 on 2022-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='is_annotated',
        ),
        migrations.AddField(
            model_name='images',
            name='annotations',
            field=models.JSONField(default=None),
        ),
    ]
