# Generated by Django 4.0.1 on 2022-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_images_is_annotated_images_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='annotations',
            field=models.JSONField(default=None, null=True),
        ),
    ]
